image: python:3

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt  # Install dependencies
    - python test.py  # Run the test script
  variables:
    LT_USERNAME: $LT_USERNAME  
    LT_ACCESS_KEY: $LT_ACCESS_KEY  
